# Mod Loading Info
modLoader="javafml"
loaderVersion="${loader_version_range}"

# Doctor Who Adventure Config
license="${mod_license}"

[[mods]]
modId="dw_adventure"
version="${mod_version}"
displayName="${mod_name}"
logoFile="dw_adventure.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

# Dependency for Forge
[[dependencies.dw_adventure]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

# Dependency for Minecraft
[[dependencies.dw_adventure]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"